# Generated by Django 2.2 on 2020-05-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Catalogo', '0006_auto_20200508_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('fabrica', models.ForeignKey(db_column='fabrica_id', on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Fabrica')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('descripcion', models.CharField(max_length=50)),
                ('pedido', models.ForeignKey(db_column='Pedido_id', on_delete=django.db.models.deletion.CASCADE, to='Pedir.Pedido')),
            ],
        ),
    ]
