# Generated by Django 2.2 on 2020-05-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallarPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('descripcion', models.CharField(max_length=50)),
                ('pedido', models.ForeignKey(db_column='Pedido_id', on_delete=django.db.models.deletion.CASCADE, to='Pedir.Pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
