# Generated by Django 2.2 on 2020-05-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20200419_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='iva',
        ),
    ]
