# Generated by Django 2.2 on 2020-05-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0005_auto_20200508_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vehiculo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Vehiculo'),
        ),
        migrations.DeleteModel(
            name='Relacion',
        ),
    ]
