# Generated by Django 2.2 on 2020-04-19 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='Facturacion.Factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
