# Generated by Django 2.2 on 2020-05-14 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0004_auto_20200507_1653'),
        ('Catalogo', '0006_auto_20200508_2008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(db_column='cliente_nombre', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('cliente_nit', models.ForeignKey(db_column='cliente_nit', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.ForeignKey(db_column='Orden_id', on_delete=django.db.models.deletion.CASCADE, to='Vender.Orden')),
                ('producto', models.ForeignKey(db_column='Producto_id', on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Producto')),
            ],
        ),
    ]
