# Generated by Django 2.2 on 2020-05-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Vender.Orden'),
        ),
    ]
