# Generated by Django 2.2 on 2020-05-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0002_facturacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='detalle',
            field=models.ForeignKey(db_column='orden', default=0, on_delete=django.db.models.deletion.CASCADE, to='Vender.Detalle'),
        ),
    ]
