# Generated by Django 2.2 on 2020-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0004_remove_facturacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
