# Generated by Django 2.2 on 2020-05-14 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clientes', '0004_auto_20200507_1653'),
        ('Vender', '0006_auto_20200514_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField()),
                ('cliente', models.ForeignKey(db_column='cliente_nombre', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
