# Generated by Django 2.2 on 2020-05-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20200507_1653'),
        ('Vender', '0007_ordenfuturo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField()),
                ('total', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('cliente_nit', models.ForeignKey(db_column='cliente_nit', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('orden', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Vender.Orden')),
            ],
        ),
    ]
