# Generated by Django 2.2 on 2020-05-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0008_credito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='fecha',
            new_name='fecha_actual',
        ),
        migrations.AlterField(
            model_name='credito',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Vender.OrdenFuturo'),
        ),
    ]
