# Generated by Django 2.2 on 2020-05-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_auto_20200513_2123'),
        ('Vender', '0009_auto_20200516_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('total', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('cliente_nit', models.ForeignKey(db_column='cliente_nit', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('factura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Vender.Facturacion')),
            ],
        ),
    ]
