# Generated by Django 2.2 on 2020-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('mayorista', 'Mayorista'), ('taller', 'Taller'), ('individual', 'Individual')], max_length=50),
        ),
    ]
