# Generated by Django 2.2 on 2020-04-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20200408_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
