# Generated by Django 2.2 on 2020-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_auto_20200419_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='patente',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
