# Generated by Django 2.2 on 2020-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20200507_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
