# Generated by Django 2.2 on 2020-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_suscripcion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
