# Generated by Django 2.2 on 2020-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_auto_20200513_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
